services:
  ansible:
    build:
      context: ./docker/ansible
      dockerfile: Dockerfile.${COMMON_ENVIRONMENT}
      args:
        - BASE_IMG_NAME=${BASE_IMG_NAME}
        - BASE_IMG_TAG=${BASE_IMG_TAG}
        - UID=${COMMON_UID}
        - GID=${COMMON_GID}
        - USERNAME=${COMMON_USERNAME}
        - COMMENT=${COMMON_COMMENT}
        - SHELL=${COMMON_SHELL}
        - TIMEZONE=${COMMON_TIMEZONE}
    container_name: ansible
    hostname: ansible
    restart: no # unless-stopped
    tty: true
    stdin_open: true
    volumes:
      - "./home:/home/${COMMON_USERNAME}"
    user: "${COMMON_USERNAME}"
    working_dir: "/home/${COMMON_USERNAME}"
    networks:
      ansible-network:
        ipv4_address: 172.16.128.10
        mac_address: "00:50:56:8E:8B:10"

  server01:
    build:
      context: ./docker/server
      dockerfile: Dockerfile.${COMMON_ENVIRONMENT}
      args:
        - BASE_IMG_NAME=${TARGET_IMG_NAME}
        - BASE_IMG_TAG=${TARGET_IMG_TAG}
        - UID=${TARGET_UID}
        - GID=${TARGET_GID}
        - USERNAME=${TARGET_USERNAME}
        - COMMENT=${TARGET_COMMENT}
        - SHELL=${TARGET_SHELL}
        - TIMEZONE=${TARGET_TIMEZONE}
    container_name: server01
    hostname: server01
    restart: no # unless-stopped
    tty: true
    stdin_open: true
    privileged: true # Required for /usr/sbin/init
    user: "${TARGET_USERNAME}"
    working_dir: "/home/${TARGET_USERNAME}"
    networks:
      ansible-network:
        ipv4_address: 172.16.128.11
        mac_address: "00:50:56:8E:8B:11"

  server02:
    build:
      context: ./docker/server
      dockerfile: Dockerfile.${COMMON_ENVIRONMENT}
      args:
        - BASE_IMG_NAME=${TARGET_IMG_NAME}
        - BASE_IMG_TAG=${TARGET_IMG_TAG}
        - UID=${TARGET_UID}
        - GID=${TARGET_GID}
        - USERNAME=${TARGET_USERNAME}
        - COMMENT=${TARGET_COMMENT}
        - SHELL=${TARGET_SHELL}
        - TIMEZONE=${TARGET_TIMEZONE}
    container_name: server02
    hostname: server02
    restart: no # unless-stopped
    tty: true
    stdin_open: true
    privileged: true # Required for /usr/sbin/init
    user: "${TARGET_USERNAME}"
    working_dir: "/home/${TARGET_USERNAME}"
    networks:
      ansible-network:
        ipv4_address: 172.16.128.12
        mac_address: "00:50:56:8E:8B:12"

  server03:
    build:
      context: ./docker/server
      dockerfile: Dockerfile.${COMMON_ENVIRONMENT}
      args:
        - BASE_IMG_NAME=${TARGET_IMG_NAME}
        - BASE_IMG_TAG=${TARGET_IMG_TAG}
        - UID=${TARGET_UID}
        - GID=${TARGET_GID}
        - USERNAME=${TARGET_USERNAME}
        - COMMENT=${TARGET_COMMENT}
        - SHELL=${TARGET_SHELL}
        - TIMEZONE=${TARGET_TIMEZONE}
    container_name: server03
    hostname: server03
    restart: no # unless-stopped
    tty: true
    stdin_open: true
    privileged: true # Required for /usr/sbin/init
    user: "${TARGET_USERNAME}"
    working_dir: "/home/${TARGET_USERNAME}"
    networks:
      ansible-network:
        ipv4_address: 172.16.128.13
        mac_address: "00:50:56:8E:8B:13"

networks:
  ansible-network:
    ipam:
      config:
        - subnet: 172.16.128.0/24
