---
- name: Add SSH keys of all managed nodes into known_hosts file
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Add SSH keys of each managed node into known_hosts of local machine
      ansible.builtin.known_hosts:
        name: "{{ hostvars[item].ansible_host }}"
        key: "{{ lookup('ansible.builtin.pipe', 'ssh-keyscan -H ' + hostvars[item].ansible_host) }}"
        path: "{{ lookup('ansible.builtin.env', 'HOME') }}/.ssh/known_hosts"
      loop: "{{ groups['all'] }}"

